### ISSUE TITLE
"cargo build --release" error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [sopium/titun#1]
hi。

yudeMacBook-Air:titun-by-sopium brite$ cargo build --release
    Updating git repository `https://github.com/sopium/noise-rust`
error: failed to load source for a dependency on `noise-protocol`

Caused by:
  Unable to update https://github.com/sopium/noise-rust?branch=sodium_aeads#51bd5e01

Caused by:
  revspec '51bd5e01c4c01bb3a6b54be40967a8eaf2d0235f' not found; class=Reference (4); code=NotFound (-3)
yudeMacBook-Air:titun-by-sopium brite$

**Comment by sopium** [comment]
I haven't updated this repository for a while. It's on GitLab now:

https://gitlab.com/sopium/titun

**Comment by sopium** [comment]
I have moved back to github. Now it should work.

**Comment by luckypoem** [comment]
how should the respective config file in client side and server side be written?
can u paste the respective config file in client side and server side in readme or here?

**Comment by sopium** [comment]
There is a pair of config files in `ns-test`: `tun1.conf` and `tun2.conf`.

Also check out these resources on wireguard.com:

https://www.wireguard.com/#conceptual-overview

https://www.wireguard.com/quickstart/

**Comment by luckypoem** [comment]
hello.

in vps:
cd /root/titun-by-sopium/target/release
cp /etc/wireguard/wg0.conf titun.conf
nano titun.conf
(i modified ListenPort's value to new-port-number)
./titun -c titun.conf tun8
it shows:
[WARN  titun::cli::config] configuration file is world readable

ps aux|grep titun
it shows:
root     13950  0.0  0.1 220696  2168 ?        Sl   16:56   0:00 ./titun -c titun.conf tun8
root     13973  0.0  0.1 112588  2268 pts/2    S+   16:56   0:00 grep --color titun

on my mac:
cd ~/titun-by-sopium/target/release
cp  /etc/wireguard/wg0.conf titun.conf
nano titun.conf
(i modified Endpoint's value to be my-vps-ip:new-port-number
sudo ./titun -c titun.conf tun6
Password:
[WARN  titun::cli::config] configuration file is world readable

ps aux|grep titun
it shows:
brite           31144   0.0  0.0  2432804    772 s004  S+    5:04下午   0:00.00 grep titun
root             31105   0.0  0.0  2472068   1788   ??  S     5:04下午   0:00.01 ./titun -c titun.conf tun6

but i still cannot cross the gfw.when i visit www.ipaddress.com ,it still shows the ip my isp assigned me.
why?how to fix it?

**Comment by sopium** [comment]
> hello.
> 
> in vps:
> cd /root/titun-by-sopium/target/release
> cp /etc/wireguard/wg0.conf titun.conf
> nano titun.conf
> (i modified ListenPort's value to new-port-number)
> ./titun -c titun.conf tun8
> it shows:
> [WARN titun::cli::config] configuration file is world readable
> 
> ps aux|grep titun
> it shows:
> root 13950 0.0 0.1 220696 2168 ? Sl 16:56 0:00 ./titun -c titun.conf tun8
> root 13973 0.0 0.1 112588 2268 pts/2 S+ 16:56 0:00 grep --color titun
> 
> on my mac:

I have never tested TiTun on Mac. Would be surprised if it works at all.

> cd ~/titun-by-sopium/target/release
> cp /etc/wireguard/wg0.conf titun.conf
> nano titun.conf
> (i modified Endpoint's value to be my-vps-ip:new-port-number
> sudo ./titun -c titun.conf tun6
> Password:
> [WARN titun::cli::config] configuration file is world readable
> 
> ps aux|grep titun
> it shows:
> brite 31144 0.0 0.0 2432804 772 s004 S+ 5:04下午 0:00.00 grep titun
> root 31105 0.0 0.0 2472068 1788 ?? S 5:04下午 0:00.01 ./titun -c titun.conf tun6
> 
> but i still cannot cross the gfw.when i visit [www.ipaddress.com](http://www.ipaddress.com) ,it still shows the ip my isp assigned me.
> why?how to fix it?

Sorry, it's a shame, but I can't help you bypass the GFW.

**Comment by briteming** [comment]
so,have u used the titun to cross the gfw on linux desktop os successfully?
