### ISSUE TITLE
mipsel linux target support?

### ISSUE THREAD

**Issue by foobartech** [sopium/titun#214]
I tried to compile titun for mipsel linux target but failed
```sh
cross build --release --target mipsel-unknown-linux-musl
```
[peer_state.rs](https://github.com/sopium/titun/blob/master/src/wireguard/peer_state.rs)
```rust
use std::sync::atomic::{AtomicU64, Ordering};
```
It seems it's because [MIPS platforms with 32-bit pointers do not have AtomicU64 type](https://doc.rust-lang.org/std/sync/atomic/index.html)

**Comment by sopium** [comment]
If it's the only problem, it should be relatively easy to fix: use `Mutex<u64>` when `AtomicU64` is not available.

Can you try the `mutex-u64-when-atomic-u64-not-available` branch?

**Comment by foobartech** [comment]
Thanks for your quick response.
I tried the `mutex-u64-when-atomic-u64-not-available` branch, compiled successfully
```sh
git clone https://github.com/sopium/titun.git -b mutex-u64-when-atomic-u64-not-available
...
file titun
titun: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), statically linked, stripped
```
works as expected!
```sh
./titun show
interface: wg0
  public key: NxC01ceW3R(hidden)TbD7ZqTzkY=
  private key: (hidden)
  listening port: 49287

peer: YJNFrgXgDCv/I0NOV6(hidden)Erx3gH6u2oHnF8=
  endpoint: (hidden):(hidden)
  allowed ips: 0.0.0.0/0
  last handshake: 13 seconds ago
  transfer: 124 B received, 180 B sent
  persistent keepalive: every 30 seconds
```
I'm ok to close this issue.

**Comment by sopium** [comment]
Glad that it works for you!
