### ISSUE TITLE
a tunnel with encryption function?

### ISSUE THREAD

**Issue by lootoos** [sopium/titun#516]
Is it possible to disable the encryption function by leaving just a tunnel so that you can open your network to the world Internet using vds?
Wireguard adds a delay because it encrypts all packets that enter its tunnel, my tunnel has the following IP: vds 10.228.228.1, home pc 10.228.228.2, everything that goes from vds to 10.228.228.2 encrypts thereby adds a delay in packet transmission thereby increasing ping

**Comment by blckngm** [comment]
It's not possible. Maybe try GRE or IPIP tunnels?

**Comment by lootoos** [comment]
Do GRE/IPIP require a white IP on a home PC?
